spring:
  application:
    name: LogiSmart

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /logismart/api

springdoc:
  swagger-ui:
    path: /public/swagger-ui

logging:
  level:
    br.com.uniexpress: ${LOG_LEVEL:DEBUG}

viacep:
  url: http://localhost:8181/stub/viacep/ws
