spring:
  application:
    name: LogiSmart

  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /logismart/api

springdoc:
  swagger-ui:
    path: /public/swagger-ui

logging:
  level:
    br.com.uniexpress: ${LOG_LEVEL:DEBUG}

viacep:
  url: https://viacep.com.br/ws
